version: '3.8'

services:
  app:
    build: .
    container_name: app_bun
    restart: unless-stopped
    ports:
      - '3333:3333'
    networks:
      - internal_net
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge

volumes:
  postgres_data:
